{% set name = "calkulate" %}
{% set version = "23.7.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/calkulate-{{ version }}.tar.gz
  sha256: 88c2f784f1c65ff3e4c5b3799e65f4792e66126035f1df9fd58e80ff4651926f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyco2sys >=1.8,<2
    - matplotlib-base
    - numpy
    - openpyxl
    - pandas
    - scipy

test:
  imports:
    - calkulate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'Calkulate: seawater total alkalinity from titration data'
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/calkulate

extra:
  recipe-maintainers:
    - mvdh7
